name: string_mask
description: A string formatter and validator based on masks.
version: 0.0.1
homepage: https://www.olimou.com
author: EmersonMoura <olimou@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
